# Generated by Django 4.1.5 on 2023-01-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=64)),
                ("apellido", models.CharField(max_length=64)),
                ("fecha_alta", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Proyectos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proyecto", models.CharField(max_length=64)),
                ("fecha_inicio", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tareas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarea", models.CharField(max_length=254)),
                ("fecha_vencimiento", models.DateField(null=True)),
            ],
        ),
    ]
